jobs:
- name: build-c3i
  public: true
  serial: true
  plan:
  - get: recipe-repo-source
    trigger: true
  - task: build-conda-package
    config:
      image_resource:
        source:
          # can't template just part of a line: https://github.com/concourse/concourse/issues/545
          repository: continuumio/anaconda-pkg-build
          tag: master
          username: ((common.dockerhub-user))
          password: ((common.dockerhub-pass))
        type: docker-image
        check_every: 1h
      inputs:
      - name: recipe-repo-source
      platform: linux
      run:
        path: conda-build
        args:
          - --no-test
          - -c
          - c3i_test
          - --token
          - {{anaconda_org_upload_token}}
          - recipe-repo-source/conda.recipe
  - task: consolidate-miniconda-docker-folder
    config:
      platform: linux
      image_resource:
        source:
          repository: continuumio/anaconda-pkg-build
          tag: master
          username: ((common.dockerhub-user))
          password: ((common.dockerhub-pass))
        type: docker-image
        check_every: 1h
      inputs:
        - name: recipe-repo-source
      outputs:
        - name: docker-build
      run:
        path: sh
        args:
          - -exc
          - |
            cp -r recipe-repo-source/docker/c3i-linux-64/* docker-build
  - put: docker-image
    params:
      build: docker-build
    get_params:
      skip_download: true

resources:
- name: docker-image
  type: docker-image
  check_every: 1h
  source:
    # can't template just part of a line: https://github.com/concourse/concourse/issues/545
    repository: continuumio/anaconda-pkg-build
    tag: master
    username: ((common.dockerhub-user))
    password: ((common.dockerhub-pass))

- name: recipe-repo-source
  type: git
  source:
    uri: {{recipe-repo}}
