groups: []
resources:
- name: rsync-build-pack
  type: rsync-resource
  source:
    base_dir: /ci/build_pack
    disable_version_path: true
    private_key: ((common.intermediate-private-key))
    server: bremen.corp.continuum.io
    user: ci
- name: rsync_build_py_script0-on-linux_64
  type: rsync-resource
  source:
    base_dir: /ci/ktietz/artifacts_py
    disable_version_path: true
    private_key: ((common.intermediate-private-key))
    server: bremen.corp.continuum.io
    user: ci
- name: rsync_build_py_script0-on-osx
  type: rsync-resource
  source:
    base_dir: /ci/ktietz/artifacts_py
    disable_version_path: true
    private_key: ((common.intermediate-private-key))
    server: bremen.corp.continuum.io
    user: ci
- name: rsync_build_py_script0-on-winbuilder
  type: rsync-resource
  source:
    base_dir: /ci/ktietz/artifacts_py
    disable_version_path: true
    private_key: ((common.intermediate-private-key))
    server: bremen.corp.continuum.io
    user: ci
resource_types:
- name: rsync-resource
  type: docker-image
  source:
    repository: conda/concourse-rsync-resource
    tag: latest
jobs:
- name: build_py_script0-on-linux_64
  plan:
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: conda/c3i-linux-64
          tag: latest
      params:
        GITHUB_TOKEN: ((common.recipe-repo-access-token))
        GITHUB_USER: SA-PCR-RO
      run:
        path: sh
        args:
        - -exc
        - conda update -y conda-build&& conda config --set add_pip_as_python_dependency
          False&& conda config --add default_channels https://repo.anaconda.com/pkgs/main&&
          conda config --add default_channels https://repo.anaconda.com/pkgs/r&& conda
          info&& set +x&& echo machine github.com login $GITHUB_USER password $GITHUB_TOKEN
          protocol https > ~/.netrc&& set -x &&
          git clone https://github.com/AnacondaRecipes/aggregate.git &&
          cd aggregate && git submodule update --init 
          autovizwidget-feedstock
          holoviews-feedstock
          rise-feedstock
          && cd .. &&
          conda update -y -n base conda && conda update -y --all &&
          conda-build --no-test --no-anaconda-upload --no-error-overlinking --output-folder=output-py_artifacts
          --python=3.8
          -c local --output-folder=output-py_artifacts --cache-dir=output-source --stats-file=stats/build_py_script0-on-linux_64_1564756033.json
          --croot . -m ./aggregate/conda_build_config.yaml
          aggregate/autovizwidget-feedstock
          aggregate/holoviews-feedstock
          aggregate/rise-feedstock
          
      outputs:
      - name: output-py_artifacts
      - name: output-source
      - name: stats
  - put: rsync_build_py_script0-on-linux_64
    params:
      rsync_opts:
      - --archive
      - --no-perms
      - --omit-dir-times
      - --verbose
      - --exclude
      - '"**/*.json*"'
      - --exclude
      - '"**/*.*ml"'
      - --exclude
      - '"**/.cache"'
      sync_dir: output-py_artifacts
    get_params:
      skip_download: true
- name: build_py_script0-on-osx
  plan:
  - get: rsync-build-pack
    params:
      rsync_opts:
      - --include
      - osx_build_env_latest.zip
      - --exclude
      - '*'
      - -v
  - task: build
    config:
      platform: darwin
      params:
        GITHUB_TOKEN: ((common.recipe-repo-access-token))
        GITHUB_USER: SA-PCR-RO
      run:
        path: sh
        args:
        - -exc
        - hostname&& pwd&& mkdir build_env&& unzip -o -q rsync-build-pack/osx_build_env_latest.zip
          -d build_env&& source build_env/bin/activate&& conda-unpack&& conda init&&
          source build_env/etc/profile.d/conda.sh&& conda config --set add_pip_as_python_dependency
          False&& conda config --add default_channels https://repo.anaconda.com/pkgs/main&&
          conda config --add default_channels https://repo.anaconda.com/pkgs/r&& conda
          info&& set +x&& echo machine github.com login $GITHUB_USER password $GITHUB_TOKEN
          protocol https > ~/.netrc&& set -x&& set +x&& echo machine github.com login
          $GITHUB_USER password $GITHUB_TOKEN protocol https > ~/.netrc&& set -x&&
          set +x&& echo machine github.com login $GITHUB_USER password $GITHUB_TOKEN
          protocol https > ~/.netrc&& set -x&& set +x&& echo machine github.com login
          $GITHUB_USER password $GITHUB_TOKEN protocol https > ~/.netrc&& set -x&&
          git clone https://github.com/AnacondaRecipes/aggregate.git &&
          cd aggregate && git submodule update --init 
          autovizwidget-feedstock
          holoviews-feedstock
          rise-feedstock
          && cd .. &&
          conda update -y -n base conda && conda update -y --all &&
          conda-build --no-test --no-anaconda-upload --no-error-overlinking --output-folder=output-py_artifacts
          --python=3.8
          --cache-dir=output-source --stats-file=stats/build_py_script0-on-osx_1564756033.json
          -c local --croot . -m ./aggregate/conda_build_config.yaml
          aggregate/autovizwidget-feedstock
          aggregate/holoviews-feedstock
          aggregate/rise-feedstock
          
      inputs:
      - name: rsync-build-pack
      outputs:
      - name: output-py_artifacts
      - name: output-source
      - name: stats
  - put: rsync_build_py_script0-on-osx
    params:
      rsync_opts:
      - --archive
      - --no-perms
      - --omit-dir-times
      - --verbose
      - --exclude
      - '"**/*.json*"'
      - --exclude
      - '"**/*.*ml"'
      - --exclude
      - '"**/.cache"'
      sync_dir: output-py_artifacts
    get_params:
      skip_download: true
- name: build_py_script0-on-winbuilder
  plan:
  - get: rsync-build-pack
    params:
      rsync_opts:
      - --include
      - windows_build_env_latest.zip
      - --exclude
      - '*'
      - -v
  - task: build
    config:
      platform: windows
      params:
        GITHUB_TOKEN: ((common.recipe-repo-access-token))
        GITHUB_USER: SA-PCR-RO
      run:
        path: cmd.exe
        args:
        - /c
        - hostname&& mkdir build_env&& echo %CD%&& echo Extracting build environment&&
          7z x ./rsync-build-pack/windows_build_env_latest.zip -o./build_env -y&&
          echo Activating build environment&& call .\build_env\Scripts\activate&&
          echo Unpacking environment&& conda-unpack&& conda config --system --set
          add_pip_as_python_dependency False&& conda config --system --add default_channels
          https://repo.anaconda.com/pkgs/main&& conda config --system --add default_channels
          https://repo.anaconda.com/pkgs/r&& conda config --system --add default_channels
          https://repo.anaconda.com/pkgs/msys2&& conda info&& (echo machine github.com
          login %GITHUB_USER% password %GITHUB_TOKEN% protocol https > %USERPROFILE%\_netrc
          || exit 0)&& (echo machine github.com login %GITHUB_USER% password %GITHUB_TOKEN%
          protocol https > %USERPROFILE%\_netrc || exit 0)&&
          git clone https://github.com/AnacondaRecipes/aggregate.git &&
          cd aggregate && git submodule update --init 
          autovizwidget-feedstock
          holoviews-feedstock
          rise-feedstock
          && cd .. &&
          conda update -y -n base conda && conda update -y --all &&
          conda-build --no-test --no-anaconda-upload --no-error-overlinking --output-folder=output-py_artifacts
          --python=3.8
          --cache-dir=output-source --stats-file=stats/build_py_script08-on-winbuilder_1564756033.json
          --croot C:\ci -c local -m aggregate/conda_build_config.yaml
          aggregate/autovizwidget-feedstock
          aggregate/holoviews-feedstock
          aggregate/rise-feedstock
          
      inputs:
      - name: rsync-build-pack
      outputs:
      - name: output-py_artifacts
      - name: output-source
      - name: stats
  - put: rsync_build_py_script0-on-winbuilder
    params:
      rsync_opts:
      - --archive
      - --no-perms
      - --omit-dir-times
      - --verbose
      - --exclude
      - '"**/*.json*"'
      - --exclude
      - '"**/*.*ml"'
      - --exclude
      - '"**/.cache"'
      sync_dir: output-py_artifacts
    get_params:
      skip_download: true
