package:
  name: conda-concourse-ci
  version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}

source:
  path: ../

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - c3i = conda_concourse_ci.cli:main

requirements:
  build:
    - python
    - setuptools
  run:
    - conda-build >=3.0.9
    - conda
    - contextlib2
    - networkx >=2.0
    - python
    - requests
    # we use pkg_resources, so yes, this is a runtime dep
    - setuptools
    - six
    - yaml

test:
  requires:
    - pytest
    - pytest-cov
    - pytest-mock
  commands:
    - py.test tests --cov conda_concourse_ci
  source_files:
    - tests

about:
  summary: Glue between conda-build and Concourse CI.  Builds repos of recipes.
  home: https://github.com/conda/conda-concourse-ci
  dev_url: https://github.com/conda/conda-concourse-ci
  doc_url: https://github.com/conda/conda-concourse-ci
  license: BSD 3-clause
